//! Route flags: the `rtm_flags` bitmask the kernel attaches to every routing
//! table entry, and the single-letter mnemonics `netstat -rn` prints for them.
//!
//! The bit values come from `<net/route.h>`; the letters and their iteration
//! order mirror the `bits[]` table in macOS's `netstat` (`route.c`), so the
//! strings we render (e.g. `UGScg`, `UGScIg`) match `netstat -rn` exactly.

use serde::Serialize;

/// Route usable — set on every live route. Used to distinguish the primary
/// default route from stale scoped duplicates (see `RTF_IFSCOPE`).
pub const RTF_UP: u32 = 0x1;

/// Route has a valid interface scope. macOS installs a per-interface,
/// IFSCOPE-tagged copy of the default route for each usable uplink; the one
/// *unscoped* default (this bit clear) is the primary route the kernel uses
/// for ordinary, non-scoped traffic.
pub const RTF_IFSCOPE: u32 = 0x1000000;

/// One flag bit and how to name it.
pub struct FlagDef {
    /// The `RTF_*` bit in `rtm_flags`.
    pub bit: u32,
    /// The single-letter mnemonic `netstat` prints.
    pub letter: char,
    /// The `RTF_*` constant name, without the prefix (e.g. `GATEWAY`).
    pub name: &'static str,
    /// One-line meaning, following the `<net/route.h>` comments (lightly
    /// adapted, e.g. LLINFO cites NDP since these routes are IPv6 in practice).
    pub description: &'static str,
}

/// All known route flags, in the order `netstat -rn` prints them. Rendering in
/// this fixed order (not bit order) is what makes our letter strings identical
/// to netstat's — e.g. multicast (`m`, a high bit) prints right after `M`.
pub const FLAGS: &[FlagDef] = &[
    FlagDef { bit: 0x1,        letter: 'U', name: "UP",        description: "route usable" },
    FlagDef { bit: 0x2,        letter: 'G', name: "GATEWAY",   description: "destination is a gateway" },
    FlagDef { bit: 0x4,        letter: 'H', name: "HOST",      description: "host entry (net otherwise)" },
    FlagDef { bit: 0x8,        letter: 'R', name: "REJECT",    description: "host or net unreachable" },
    FlagDef { bit: 0x10,       letter: 'D', name: "DYNAMIC",   description: "created dynamically (by redirect)" },
    FlagDef { bit: 0x20,       letter: 'M', name: "MODIFIED",  description: "modified dynamically (by redirect)" },
    FlagDef { bit: 0x800000,   letter: 'm', name: "MULTICAST", description: "route represents a mcast address" },
    FlagDef { bit: 0x40,       letter: 'd', name: "DONE",      description: "message confirmed" },
    FlagDef { bit: 0x100,      letter: 'C', name: "CLONING",   description: "generate new routes on use" },
    FlagDef { bit: 0x200,      letter: 'X', name: "XRESOLVE",  description: "external daemon resolves name" },
    FlagDef { bit: 0x400,      letter: 'L', name: "LLINFO",    description: "generated by link layer (e.g. NDP)" },
    FlagDef { bit: 0x800,      letter: 'S', name: "STATIC",    description: "manually added" },
    FlagDef { bit: 0x8000,     letter: '1', name: "PROTO1",    description: "protocol specific routing flag" },
    FlagDef { bit: 0x4000,     letter: '2', name: "PROTO2",    description: "protocol specific routing flag" },
    FlagDef { bit: 0x20000,    letter: 'W', name: "WASCLONED", description: "route generated through cloning" },
    FlagDef { bit: 0x10000,    letter: 'c', name: "PRCLONING", description: "protocol requires cloning" },
    FlagDef { bit: 0x40000,    letter: '3', name: "PROTO3",    description: "protocol specific routing flag" },
    FlagDef { bit: 0x1000,     letter: 'B', name: "BLACKHOLE", description: "just discard pkts (during updates)" },
    FlagDef { bit: 0x400000,   letter: 'b', name: "BROADCAST", description: "route represents a bcast address" },
    FlagDef { bit: 0x1000000,  letter: 'I', name: "IFSCOPE",   description: "has valid interface scope" },
    FlagDef { bit: 0x4000000,  letter: 'i', name: "IFREF",     description: "route holds a ref to interface" },
    FlagDef { bit: 0x8000000,  letter: 'Y', name: "PROXY",     description: "proxying, no interface scope" },
    FlagDef { bit: 0x10000000, letter: 'r', name: "ROUTER",    description: "host is a router" },
    FlagDef { bit: 0x40000000, letter: 'g', name: "GLOBAL",    description: "route to destination of the global internet" },
];

/// The `netstat`-style letter string for a flags bitmask, e.g. `UGScg`.
/// A route with no recognised bits set renders as a single `-`.
pub fn letters(flags: u32) -> String {
    let s: String = FLAGS
        .iter()
        .filter(|f| flags & f.bit != 0)
        .map(|f| f.letter)
        .collect();
    if s.is_empty() { "-".to_string() } else { s }
}

/// One decoded flag, for the `--json` output.
#[derive(Serialize)]
pub struct DecodedFlag {
    pub flag: char,
    pub name: &'static str,
    pub description: &'static str,
}

/// Every set flag, decoded to (flag, name, description) in netstat order.
pub fn decode(flags: u32) -> Vec<DecodedFlag> {
    FLAGS
        .iter()
        .filter(|f| flags & f.bit != 0)
        .map(|f| DecodedFlag { flag: f.letter, name: f.name, description: f.description })
        .collect()
}
