//! Reading the macOS kernel routing table, with flags.
//!
//! We dump the table ourselves via `sysctl(NET_RT_DUMP)` and parse the
//! `rt_msghdr` + trailing `sockaddr` list. This is the same mechanism the
//! `net-route` crate (and `netstat -rn`) use, but we keep the `rtm_flags`
//! field that `net-route`'s `Route` type drops — flags are the whole point of
//! this module. The sockaddr-parsing logic mirrors `net-route`'s macOS backend
//! (which in turn follows Apple's `route.c`), so destinations, prefixes, and
//! gateways come out byte-for-byte identical to what that crate produced.

use std::io;
use std::mem;
use std::net::{IpAddr, Ipv6Addr};

use libc::{
    c_int, c_void, rt_msghdr, size_t, sockaddr, sockaddr_in, sockaddr_in6, AF_INET, AF_INET6,
    AF_ROUTE, CTL_NET, NET_RT_DUMP, RTM_VERSION,
};

// Indices into the address list carried after each `rt_msghdr`, and the bits in
// `rtm_addrs` that say which are present. `libc` exposes `RTAX_MAX` but not the
// individual indices, so we spell out the ones we read.
const RTAX_DST: usize = 0;
const RTAX_GATEWAY: usize = 1;
const RTAX_NETMASK: usize = 2;

/// `RTF_WASCLONED`: routes the kernel generated by cloning (ARP/ND entries and
/// the like). `netstat -rn` hides them and so do we — they're runtime cache
/// state, not configured routes.
const RTF_WASCLONED: u32 = 0x20000;

/// One raw routing-table entry, including the `rtm_flags` bitmask.
pub struct RawRoute {
    pub destination: IpAddr,
    pub prefix: u8,
    pub gateway: Option<IpAddr>,
    pub ifindex: Option<u32>,
    pub flags: u32,
}

/// Dump and parse the whole routing table (both families). Requires no
/// privileges — reading the routing table is unprivileged on macOS.
pub fn route_table() -> io::Result<Vec<RawRoute>> {
    let (buf, len) = dump_table()?;

    let mut routes = Vec::new();
    let mut offset = 0;

    // Walk the concatenated routing messages. Each starts with an `rt_msghdr`
    // whose `rtm_msglen` gives the stride to the next one; trust the `len` that
    // sysctl reported, which can be shorter than the buffer we allocated.
    while offset + mem::size_of::<rt_msghdr>() <= len {
        let hdr = unsafe { &*buf.as_ptr().add(offset).cast::<rt_msghdr>() };
        if hdr.rtm_version as c_int != RTM_VERSION {
            // Not a routing message we understand; stop rather than misparse.
            break;
        }

        let msg_len = hdr.rtm_msglen as usize;
        if msg_len == 0 || offset + msg_len > len {
            break;
        }
        let body = &buf[offset + mem::size_of::<rt_msghdr>()..offset + msg_len];
        offset += msg_len;

        // Skip cloned routes, matching `netstat -rn`.
        if hdr.rtm_flags as u32 & RTF_WASCLONED != 0 {
            continue;
        }

        if let Some(route) = message_to_route(hdr, body) {
            routes.push(route);
        }
    }

    Ok(routes)
}

/// Parse one routing message body (the `sockaddr` list) into a `RawRoute`.
/// Returns `None` for messages without a destination address.
fn message_to_route(hdr: &rt_msghdr, body: &[u8]) -> Option<RawRoute> {
    if hdr.rtm_addrs & (1 << RTAX_DST) == 0 {
        return None;
    }

    // The body is a packed list of `sockaddr`s, one per bit set in `rtm_addrs`,
    // each padded up to a 4-byte boundary (the ROUNDUP() in Apple's route.c).
    let max = libc::RTAX_MAX as usize;
    let mut addrs: Vec<Option<&sockaddr>> = vec![None; max];
    let mut pos = 0;
    for (idx, slot) in addrs.iter_mut().enumerate() {
        if hdr.rtm_addrs & (1 << idx) == 0 {
            continue;
        }
        if pos + mem::size_of::<sockaddr>() > body.len() {
            break;
        }
        let sa = unsafe { &*body.as_ptr().add(pos).cast::<sockaddr>() };
        *slot = Some(sa);
        let aligned = if sa.sa_len == 0 { 4 } else { ((sa.sa_len as usize - 1) | 0x3) + 1 };
        pos += aligned;
    }

    let destination = sa_to_ip(addrs[RTAX_DST]?)?;

    // Gateway, with the KAME-embedded scope id stripped out of link-local /
    // scoped-multicast v6 gateways (mirrors net-route; the caller re-derives
    // the zone from the route's interface).
    let gateway = match addrs[RTAX_GATEWAY] {
        Some(sa) => sa_to_ip(sa).map(strip_gateway_zone),
        None => None,
    };

    // Prefix length, decoded from the netmask sockaddr's leading ones. A host
    // route omits the netmask (full-width prefix); a `/0` shows up as either a
    // missing mask body or an `sa_len` of 0.
    let full = if destination.is_ipv4() { 32 } else { 128 };
    let prefix = if hdr.rtm_addrs & (1 << RTAX_NETMASK) == 0 {
        full
    } else {
        match addrs[RTAX_NETMASK] {
            None => 0,
            Some(sa) if sa.sa_len == 0 => 0,
            Some(sa) => mask_to_prefix(sa, destination.is_ipv4()),
        }
    };

    Some(RawRoute {
        destination,
        prefix,
        gateway,
        ifindex: Some(hdr.rtm_index as u32),
        flags: hdr.rtm_flags as u32,
    })
}

/// Interpret a `sockaddr` as an IP address (`AF_INET` / `AF_INET6`); `None` for
/// link-layer and other families.
fn sa_to_ip(sa: &sockaddr) -> Option<IpAddr> {
    match sa.sa_family as c_int {
        AF_INET => {
            let inet = unsafe { &*(sa as *const sockaddr as *const sockaddr_in) };
            // s_addr is stored in network byte order, so its in-memory bytes
            // are the address octets already.
            Some(IpAddr::from(inet.sin_addr.s_addr.to_ne_bytes()))
        }
        AF_INET6 => {
            let inet6 = unsafe { &*(sa as *const sockaddr as *const sockaddr_in6) };
            Some(IpAddr::from(inet6.sin6_addr.s6_addr))
        }
        _ => None,
    }
}

/// Count the leading ones of a netmask sockaddr to get a prefix length.
fn mask_to_prefix(sa: &sockaddr, is_v4: bool) -> u8 {
    if is_v4 {
        let m = unsafe { &*(sa as *const sockaddr as *const sockaddr_in) };
        u32::from_be(m.sin_addr.s_addr).leading_ones() as u8
    } else {
        let m = unsafe { &*(sa as *const sockaddr as *const sockaddr_in6) };
        u128::from_be_bytes(m.sin6_addr.s6_addr).leading_ones() as u8
    }
}

/// Zero the scope id that the macOS kernel embeds in the second 16-bit group of
/// link-local and interface/link-local-multicast v6 gateway addresses (the KAME
/// convention), leaving the real gateway address.
fn strip_gateway_zone(ip: IpAddr) -> IpAddr {
    let IpAddr::V6(v6) = ip else { return ip };
    let segs = v6.segments();
    let is_unicast_ll = (segs[0] & 0xffc0) == 0xfe80;
    let is_multicast = (segs[0] & 0xff00) == 0xff00;
    let multicast_scope = segs[0] & 0x000f;
    if is_unicast_ll || (is_multicast && (multicast_scope == 1 || multicast_scope == 2)) {
        let mut clean = segs;
        clean[1] = 0;
        IpAddr::V6(Ipv6Addr::from(clean))
    } else {
        ip
    }
}

/// Call `sysctl(NET_RT_DUMP)` twice — once to size the table, once to read it —
/// returning the buffer and the byte length sysctl actually filled.
fn dump_table() -> io::Result<(Vec<u8>, usize)> {
    // CTL_NET.AF_ROUTE.0.0.NET_RT_DUMP.0 — family 0 means both v4 and v6.
    let mut mib: [c_int; 6] = [CTL_NET, AF_ROUTE, 0, 0, NET_RT_DUMP, 0];

    // A route can be added between the sizing and reading calls, growing the
    // table past the size we were told; retry a few times if that happens.
    for _ in 0..5 {
        let mut len: size_t = 0;
        let rc = unsafe {
            libc::sysctl(mib.as_mut_ptr(), 6, std::ptr::null_mut(), &mut len, std::ptr::null_mut(), 0)
        };
        if rc < 0 {
            return Err(io::Error::last_os_error());
        }

        let mut buf = vec![0u8; len];
        let rc = unsafe {
            libc::sysctl(
                mib.as_mut_ptr(),
                6,
                buf.as_mut_ptr() as *mut c_void,
                &mut len,
                std::ptr::null_mut(),
                0,
            )
        };
        if rc < 0 {
            // ENOMEM means the table outgrew our buffer; re-size and retry.
            if io::Error::last_os_error().raw_os_error() == Some(libc::ENOMEM) {
                continue;
            }
            return Err(io::Error::last_os_error());
        }
        return Ok((buf, len));
    }

    Err(io::Error::other("routing table kept growing during read"))
}
